name: eldorado
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dart_either: ^2.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  freezed_annotation:  ^2.0.0    # Requerido para anotaciones 
  get_it: ^8.2.0
  go_router: ^16.3.0
  injectable: ^2.5.2
  injector: ^4.0.0
  json_annotation:  ^4.8.0   # Requerido para la serializaci贸n JSON

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:  ^2.0.0         # Herramienta de generaci贸n de c贸digo 
  freezed:  ^2.0.0             # Congelado para datos inmutables y tipos de uni贸n 
  json_serializable:  ^6.0.0 
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/background.png
    - assets/fiat_currencies/
    - assets/cripto_currencies/